server:
  port: 8080
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: customer_route
          uri: http://localhost:8081
          predicates:
            - Path=/customers/**
        - id: order_route
          uri: http://localhost:8082
          predicates:
            - Path=/orders/**