server:
  port: 2023
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: customer_route
          uri: http://localhost:8081
          predicates:
            - Path=/customers/**
        - id: reservations_route
          uri: http://localhost:8082
          predicates:
            - Path=/reservations/**
        - id: hotel_management_route
          uri: http://localhost:8083
          predicates:
            - Path=/rooms/**
        - id: payments_route
          uri: http://localhost:8084
          predicates:
            - Path=/payments/**