server:
  port: 8888

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: product_service
          uri: http://localhost:8081
          predicates:
            - Path=/products/**
        - id: inventory_service
          uri: http://localhost:8083
          predicates:
            - Path=/inventory/**
