server:
  port: 8888

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: account_service
          uri: http://localhost:8080
          predicates:
            - Path=/accounts/**
        - id: transaction_service
          uri: http://localhost:8081
          predicates:
            - Path=/transaction/**
