server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: aggregator_service
          uri: http://localhost:9090
          predicates:
            - Path=/aggregate/**
